# Generated by Django 3.2 on 2023-11-01 01:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Мин. кол-во ингредиентов 1'), django.core.validators.MaxValueValidator(10000, message='Макс. кол-во ингредиентов 10000')], verbose_name='Количество'),
        ),
    ]
